### ISSUE TITLE
Bevaring av category-dtype hvor categories er av numeriske typer? Mulig mellom dp.write_pandas() og dp.read_pandas()?

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/dapla-ipython-kernels#25]
Se dette [demo-arket](https://github.com/statisticsnorway/SSB-Idea-repository/blob/klass-korrespondanse-merge-ipywidgets/Python/processing/dtypeconversion_bug_dapla.ipynb) for nærmere forklaring.

[Slack-tråd](https://ssb-norge.slack.com/archives/C015E7B4YS0/p1624524838131900)

Når en "category" dtype går ut og inn av daplalagringen, mister vi den om den er av numeriske typer, ser det ut til.
Dette kan omgås ved å konvertere til string, før man konverterer til category.
Men det begrenser bruken av "category" dtypes noe, for alt må encodes som strings, det betyr at vi ikke kan regne på dem, og få besparelsene som kommer med å bruke datatypen, slik man kanskje ønsker.

**Comment by bjornandre** [comment]
Related issue https://issues.apache.org/jira/browse/ARROW-11157
